# Generated by Django 2.1.2 on 2018-11-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_pictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Img',
        ),
    ]
