# Generated by Django 2.1.2 on 2018-11-26 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20181125_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
